### ISSUE TITLE
Can we adopt this package?

### ISSUE THREAD

**Issue by timabbott** [edwardgeorge/virtualenv-clone#29]
Hey @edwardgeorge, it seems this repository isn't being updated, I imagine because you don't have time anymore.  We use this project in Zulip (github.com/zulip/zulip/), and would really like to have another release come out with some bugs fixes.  Can we take over managing this package here and on pypi?  

Thanks for your consideration!

**Comment by edwardgeorge** [comment]
Hi, @timabbott 

Yeah, I've not been working with python professionally for a few years now.
I've been meaning to offer this project up for adoption.

I'll add you to this repo. I'm not sure how to transfer control on pypi it's a long time since i've logged in there. If you send me a link to some instructions and your pypi username I'll do that too.

**Comment by timabbott** [comment]
@edwardgeorge sounds good (and sorry for the slow reply; I was on a trip to Italy).  I'll do some fixes here and then ping you about the pypi upload.

**Comment by timabbott** [comment]
OK I went ahead and did a bit of cleanup of the issue tracker, merging a few fixes.   

On pypi, I'm tabbott, and basically you want to login, click the package on the right side of the page, and click on "roles" in the to-center to get their janky UI for adding another package owner.

https://pypi.python.org/pypi?:action=role_form&package_name=virtualenv-clone is probably a direct link once you're logged in, but I don't have the permissions to test it :).

Thanks @edwardgeorge!

**Comment by edwardgeorge** [comment]
hi @timabbott I just added you as an owner on pypi.
let me know if you need anything with this repo, I added you as a collaborator but looks like I can't give full admin rights on non-organisation repos?

**Comment by edwardgeorge** [comment]
I _could_ create a new virtualenv-clone org and transfer this to that and add you as admin there?

**Comment by timabbott** [comment]
Yeah, I guess the other approach is that you could transfer ownership to me (and then I could transfer it into the Zulip org), and then I could add you as an admin for this repo in the Zulip org.
