### ISSUE TITLE
Problem in fixup_pth_file()

### ISSUE THREAD

**Issue by JAdata** [edwardgeorge/virtualenv-clone#32]
There is a problem when the method fixup_pth_file() has to rewrite a file - every line is decoded from utf-8 using unicode internally, but the file is written as a unicode file at the end - no encode('utf-8') when writing.

**Comment by timabbott** [comment]
@JAdata interesting; I haven't seen this issue.  Would you be up for contributing a change for fixing this, with a test?

**Comment by JAdata** [comment]
I found a number of problems:
- There was no test coverage on the method fixup_pth_file(). 
- Wrote a new test and it immediately failed under python3.
- Fixed the issues concerning unicode output
- Also found issues concerning missing line endings when having multiple lines in the pth file.

I'm fairly new to github Pull Requests and Travis. 
- I have cloned the source, checked out a local branch and done my fixes.
- How do I commit? Push my local branch and ask for a Pull Request? Against which branch, master or lastreleasedversion - I branched from master...
- From the commit history it seems travis has been enabled recently. Can I run travis locally to ensure it will pass on github? - How?
- I have run good ol' tox and now all tests pass on all platforms...

Please advise...

**Comment by timabbott** [comment]
Awesome!

If you make a pull request, Travis will run against it automatically and display on the pull request a few minutes later.  It also works to sign up your fork for Travis and push a remote branch, but there's no reason not to do the PR (you can put "WIP" in the title if it isn't ready for review yet).

This isn't part of the zulip project but http://zulip.readthedocs.io/en/latest/git-guide.html should help answer your questions about how Git/GitHub works, making a PR, etc.

**Comment by JAdata** [comment]
Added Pull Request #33

**Comment by JAdata** [comment]
@timabbott - what happens now? PR#33 needs merging if approved and a new distribution/wheel needs to be created - do you have "the powers"...?

**Comment by timabbott** [comment]
I can merge to master, though I'm somewhat new to the package, and @edwardgeorge hasn't given me `pip` access yet.

**Comment by JAdata** [comment]
Just created a new Pull Request #34 with most of your requests satisfied @timabbott .

**Comment by timabbott** [comment]
This was fixed in #34.  Thanks for the report and PR!
