### ISSUE TITLE
pypi is missing 0.3.0 release

### ISSUE THREAD

**Issue by isbjorn** [edwardgeorge/virtualenv-clone#36]
Dear @timabbott 
Is it possible to publish 0.3.0 to pypi? 

https://pypi.python.org/pypi/virtualenv-clone

**Comment by timabbott** [comment]
@isbjorn thanks for the ping!  Yes, we should do this.  @eeshangarg can you take care of this?

**Comment by eeshangarg** [comment]
@isbjorn, @timabbott: Just made a new release <https://pypi.python.org/pypi/virtualenv-clone>. :) Sorry for the late response!
