### ISSUE TITLE
Source tarball of 0.4.0 release

### ISSUE THREAD

**Issue by foutrelis** [edwardgeorge/virtualenv-clone#42]
I was unable to find a source tarball for the 0.4.0 release. It would be convenient for Linux distro packaging to have it available. (Similar to `virtualenv-clone-0.3.0.tar.gz` on PyPI.)

**Comment by timabbott** [comment]
@eeshangarg can you post this?

**Comment by eeshangarg** [comment]
@timabbott, @foutrelis: Done! See <https://pypi.org/project/virtualenv-clone/#files> :)

**Comment by timabbott** [comment]
Great, closing.  @eeshangarg if you want to add a "release checklist" to this project's docs (probably just in a section near the bottom of README.md), that might be good to avoid us forgetting next time.
