### ISSUE TITLE
sys_path fixer not working in Python 3

### ISSUE THREAD

**Issue by vanderwb** [edwardgeorge/virtualenv-clone#48]
Issue is in virtualenv-clone/0.5.0 and was discovered while using Python 3.6.8.

If there are elements to be fixed in the sys.path, code is triggered that doesn't work in Python 3. Specifically, _virtualenv_sys calls the filter method to return the sys.path from the VE python binary. In Python 2, this is returned as a list, but in Python 3 it is returned as a consumable iterable. The sys_path iterable is consumed in line 83:

if has_old(sys_path)

So when it is used again it is equal to an empty set in line 238:

for path in syspath:

The simple fix should be to convert the iterable to a list, which will make the logic work in Python 3 and should have no impact in Python 2. I will submit a pull request for this change.

**Comment by timabbott** [comment]
I've been using this package with Python 3 for some time, so this is a corner case.  It'd be great to include a test in the fix so that we don't have to worry about breaking this in a future refactor.

**Comment by vanderwb** [comment]
I have as well, and up until yesterday hadn't encountered it, so definitely a corner case.

A test sounds good, and I'm happy to add it to my pull request, but I'm wondering what complexity you are looking for. It's pretty easy to add a list assertion to test_virtualenv_syspath that would catch this, but a significant refactor might make that assertion moot.

A more direct but complex test would be writing a pth file in test_clone_contents, and then checking that the venv path is switched from the old to the new path in the cloned pth file.

Thoughts?

**Comment by timabbott** [comment]
I think either is fine; I don't think we're super likely to do major refactors anytime soon, since the package works great as-is; and that former test would at last flag this as a case to remember even if the refactor would require changes to the test.

**Comment by vanderwb** [comment]
Sounds good to me. I've added the list assertion to the pull request.

**Comment by vanderwb** [comment]
Tim, I just did a recent pip install of this that installed 0.5.1, which I think is the version you put up after accepting the PR, but it seems to still have the bug in it. Just looking for a sanity check if nothing else.

**Comment by timabbott** [comment]
@eeshangarg can you investigate?

**Comment by eeshangarg** [comment]
@vanderwb: So, it turns out that version 0.5.1 actually didn't include this change. Anyway, I opened #52, and once it is merged, I will make a new release, after which this should be fixed. :)

@timabbott: Could you please merge #52 so that I can make a new release? Thanks! :)

**Comment by eeshangarg** [comment]
@timabbott, @vanderwb: I just made a new release and this issue should be fixed now! :) Thanks!

**Comment by vanderwb** [comment]
Just tested a pip install of it and it looks good. Thanks!
