### ISSUE TITLE
Pypi repo tarball incorrect for version 0.5.6

### ISSUE THREAD

**Issue by Admasnd** [edwardgeorge/virtualenv-clone#71]
The tarball for version 0.5.6 differs in pypi vs github. Pypi's tarball is particularly missing tox.ini which is necessary to run tests when packaging this library for GNU Guix. 

The difference between pypi can be confirmed by comparing the checksums for the two. In pypi, the checksum is 997c7d225eabc4d09e77672461f4bdf9f3a8ea9dc9e4a847b0e83dc8bad9573a. However, github's checksum for tarball is 949777a53fd8284819110661abb8f6a97420919bda34ee01353c8e3793486a28. Both checksums use sha256 and are base16 formatted. 
I used the following commands to determine this.
`guix download -H sha256 -f base16 https://files.pythonhosted.org/packages/a9/bb/ab59bdb1dc8e14add54c70e9bccb8d54379bdf73ec8cebbbf638ab76590f/virtualenv-clone-0.5.6.tar.gz`
`guix download -H sha256 -f base16 https://github.com/edwardgeorge/virtualenv-clone/archive/refs/tags/0.5.6.tar.gz`

My current workaround is to grab the tarball from github rather than pypi.

**Comment by Admasnd** [comment]
It should also be noted that the pypi download link from obtained from https://pypi.org/project/virtualenv-clone/#modal-close. On this page, you can also view the sha256 checksum which is the same as my initial post.

**Comment by timabbott** [comment]
@eeshangarg can you investigate what happened here?

**Comment by timabbott** [comment]
#72 should fix this for future releases.

**Comment by eeshangarg** [comment]
@Admasnd @timabbott The latest release just went out. This should now be fixed.
